title: Delight Lee
logo: |
  <div class="profile logo">
    <img src="/assets/images/delight_lee_profile.jpg" style="width:100px; height:100px; border-radius:50%;"/>
  </div>
theme: jekyll-theme-minimal
